name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  APPEALS_BOT_TOKEN: "000000:dummy-token-for-ci"
  MAIN_GROUP_ID: "-1001234567890"
  ADMIN_GROUP_ID: "-1000987654321"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install deps
        run: pip install -e ".[dev,test]"
      - name: flake8
        run: flake8 src tests

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install deps
        run: pip install -e ".[dev,test]"
      - name: mypy
        run: mypy src

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install deps
        run: pip install -e ".[test]"
      - name: Run tests
        run: pytest -q

